dataset:
  name: SP_celebahq
  split_names: [train, test]
  num_classes: 2
  pre_size: 112
  image_size: 256
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  mode: SP
  train:
    dataset_class: ImglistDataset_SP
    data_dir: 
    imglist_pth: ./data/SP_new3/celebahq112_train.labels.txt
    batch_size: 32
    shuffle: True
    interpolation: bilinear

  test:
    dataset_class: ImglistDataset
    batch_size: 32
    shuffle: False
    interpolation: bilinear

    set_names: [Real, Gradient-advs]
    Real:
      data_dir: 
      imglist_pth: ./data/SP_new3/celebahq_test.labels.txt
    Gradient-advs:
      subsets: [fgsm, bim, pgd, rfgsm, difgsm, mifgsm, tifgsm, tipim]
      fgsm:
        data_dir: 
        imglist_pth: ./data/SP_new3/celebahq-FGSM-eps5_test.labels.txt
      bim:
        data_dir: 
        imglist_pth: ./data/SP_new3/celebahq-BIM-eps5_test.labels.txt
      pgd:
        data_dir: 
        imglist_pth: ./data/SP_new3/celebahq-PGD-eps5_test.labels.txt
      rfgsm:
        data_dir: 
        imglist_pth: ./data/SP_new3/celebahq-RFGSM-eps5_test.labels.txt
      difgsm:
        data_dir: 
        imglist_pth: ./data/SP_new3/celebahq-DIFGSM-eps5_test.labels.txt
      mifgsm:
        data_dir: 
        imglist_pth: ./data/SP_new3/celebahq-MIFGSM-eps5_test.labels.txt
      tifgsm:
        data_dir: 
        imglist_pth: ./data/SP_new3/celebahq-TIFGSM-eps5_test.labels.txt
      tipim:
        data_dir: 
        imglist_pth: ./data/SP_new3/celebahq-TIPIM-eps5_test.labels.txt
